### ISSUE TITLE
Disable debug Enabled on iOS

### ISSUE THREAD

**Issue by Venkat1128** [usabilla/usabilla-u4a-react-native#146]
In the module initialization in the UsabillaBridge.swift file debug is always set to true  ("Usabilla.debugEnabled = true " ) but shouldn’t it be false?

**Comment by eduakaszas** [comment]
Hi @Venkat1128 , 

Thank you for reaching out.

The project is open source, therefore it's possible for our customers to remove or modify that line of code. We are only printing logs in debug mode.

That being said, we've created a feature request about this and our developers will work on adding a bridge method that will allow you to toggle debug mode. 

We'll let you know once that's ready.

Kind regards, 
Édua

**Comment by eduakaszas** [comment]
Hi @Venkat1128 , 

Thank you for your patience. 

This issue has been fixed in the latest release of our SDK. You can now enable/disable the feature using `Usabilla.setDebugEnabled(boolean)`

Kind regards, 
Édua
