### ISSUE TITLE
`onBackPress` does not exist as an export

### ISSUE THREAD

**Issue by tom-sherman** [usabilla/usabilla-u4a-react-native#150]
The docs on handling Android back button presses says to use a `onBackPressed` method, but no such method exists in the source code or installed package from `npm`.

**Comment by kioli** [comment]
Good day @tom-sherman and thank you for opening this issue

Could I please know the version of our React-Native bridge you are using?

**Comment by tom-sherman** [comment]
We're using latest, 0.14.0
