### ISSUE TITLE
Failure to compile on Android

### ISSUE THREAD

**Issue by tom-sherman** [usabilla/usabilla-u4a-react-native#154]
We have begun receiving errors when building android in our app that includes usabilla

```
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':usabilla-react-native:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':usabilla-react-native:debugCompileClasspath'.
   > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api, org.jetbrains.kotlin.platform.type=jvm}.
      > Execution failed for JetifyTransform: /Users/tomsherman/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
         > Failed to transform '/Users/tomsherman/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).
```

After removing the usabilla dependency the app builds successfully.

We also get a similar error for release builds:

```
INFO [2022-02-23 15:59:34.86]: ▸ Execution failed for task ':usabilla-react-native:compileReleaseJavaWithJavac'.
INFO [2022-02-23 15:59:34.86]: ▸ > Could not resolve all files for configuration ':usabilla-react-native:releaseCompileClasspath'.
INFO [2022-02-23 15:59:34.86]: ▸ > Failed to transform moshi-1.13.0.jar (com.squareup.moshi:moshi:1.13.0) to match attributes ***artifactType=android-classes-jar, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.jvm.environment=standard-jvm, org.gradle.jvm.version=8, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api, org.jetbrains.kotlin.platform.type=jvm***.
INFO [2022-02-23 15:59:34.86]: ▸ > Execution failed for JetifyTransform: /Users/administrator/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar.
INFO [2022-02-23 15:59:34.86]: ▸ > Failed to transform '/Users/administrator/.gradle/caches/modules-2/files-2.1/com.squareup.moshi/moshi/1.13.0/da685586facab9eb5c4fb630ce248be14e7da21b/moshi-1.13.0.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 60. (Run with --stacktrace for more details.)
```

**Comment by tutts** [comment]
hello, I'm seeing the same issue, but there is a precursor error to the one above.

It appears that ubform is using app-compat 1.4.1, which forces us to bump the sdk version to 31. After updating in grade then the error above appears.

The error prior to that is:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.appcompat:appcompat:1.4.1.
     AAR metadata file: /Users/tutts/.gradle/caches/transforms-3/f26744554353a4b7b74f5d3892fd316f/transformed/appcompat-1.4.1/META-INF/com/android/build/gradle/aar-metadata.properties.
 ```

**Comment by ConorLindsay94** [comment]
I saw the same error when upgrading React Native to 0.66.4 from 0.65.1.

There is an issue on google's issue tracker regarding the root cause of this: https://issuetracker.google.com/issues/159151549#comment12

I got around this error by setting both `compileSdkVersion` and `targetSdkVersion` to 31 but then also using AGP 7.1.0 as mentioned in that comment above.

```
android/build.gradle
...
    dependencies {
        classpath("com.android.tools.build:gradle:7.1.0")
```

**Comment by tutts** [comment]
I've managed to get it to work without upgrading if anyone finds this of interest:

in `build.gradle` add this:

```
    implementation('com.usabilla.sdk:ubform:7.3.7') {
        force = true
    }
```

and then in `grade.properties`

```
android.jetifier.ignorelist=moshi-1.13.0.jar
```

**Comment by tom-sherman** [comment]
Interesting, I had to do 3 changes to fix this in our app:

- Ignore moshi from jetifier transforms using `android.jetifier.ignorelist` in gradel.properties
- Bump `compileSdkVersion` to 31
- This surfaced another issue (https://github.com/facebook/react-native/issues/31572) which I fixed by pinning appcompat to 1.3.1

```
implementation ("androidx.appcompat:appcompat:1.3.1") {
    version {
        strictly '1.3.1'
    }
}
```

**Comment by saeedtkh** [comment]
@tom-sherman any news on this issue?

**Comment by tom-sherman** [comment]
I am waiting for Usabilla support to respond to my ticket. Ideally I don't want go forward with the above changes in our app, especially as the issue is definitely caused by including Usabilla as a dependency.

**Comment by lennardtastic** [comment]
Hi @tom-sherman,

Our apologies that no one got back to you yet here on Github. Normally, someone from the support team would reach out to you but I suspect this issue slipped through. Maybe the support team already got back to you via email? Nonetheless, I would like to provide you with an update on the matter.

As you've already highlighted the specific issue seems to be related to AppCompat 1.4. Since the issue seems to not be fixed React Native itself any time soon (see https://github.com/facebook/react-native/issues/31572#issuecomment-1030881705) we'll be issuing a fix on our side. 

To address this we'll make sure that we rely on AppCompat 1.3.1 we'll need to issue 2 releases for this (one for the Bridge and one of the Android SDK itself). As soon as the release is available I'll post an update here. 

If you have any further questions regarding this issue please do not hesitate to reach out.

**Comment by tom-sherman** [comment]
Can confirm that v0.15.1 fixed this issue for us.
