### ISSUE TITLE
Support For ios Dark Mode

### ISSUE THREAD

**Issue by SherifMega** [usabilla/usabilla-u4a-react-native#156]
package still not support dark mode for ios, any hope for changes soon ?

**Comment by stodorovicc** [comment]
HI @shrief1234567899 ,

Thanks for reaching out, I'm happy to help.

We already have available dark mode via our webeditor in GetFeedback Dashboard(in advanced settings of the form/campaign) and on our latest version of iOS SDK(from v6.10.0 onwards).

Hope that helps and let me know if you have any more questions.

Thanks,
Slobodan

**Comment by shrief1234567899** [comment]
> 
<img width="883" alt="Screen Shot 2022-03-03 at 11 18 08 AM" src="https://user-images.githubusercontent.com/32880766/156534697-fc8ee90a-6dd0-4ef8-be04-a91d0934263a.png">

thank you for your reply
but the latest version ready in package is 6.5+ , what about this ?

**Comment by stodorovicc** [comment]
@shrief1234567899,

Yes, that fetches the latest minor & patch versions. If you are on older version, you can try `cd ios && pod outdated` and after that you can try `pod update Usabilla`. Please also see attached screenshots.
<img width="718" alt="Screenshot 2022-03-03 at 10 27 45" src="https://user-images.githubusercontent.com/92579341/156537432-6ca69c78-f1c6-4305-9615-4a7794352c49.png">
<img width="563" alt="Screenshot 2022-03-03 at 10 28 28" src="https://user-images.githubusercontent.com/92579341/156537446-e86d6907-1d9a-467f-82a7-233e91ba9065.png">

Let me know if that worked for you.

Thanks,
Slobodan

**Comment by SherifMega** [comment]
great, thank you!
every thing works fine now
