### ISSUE TITLE
Detect whether a form is open

### ISSUE THREAD

**Issue by tom-sherman** [usabilla/usabilla-u4a-react-native#166]
When handling the back button presses on Android we need a way to detect whether a form is open. We must return `true` from the `hardwareBackPress` handler when the form is open in order to prevent going back in our app, and false otherwise (let the event pass).

We implement this with code like the following:

```js
let isFormOpen = false
function loadFormWithVars(form, vars) {
  Usabilla.loadFormWithVars(form, vars)
  isFormOpen = true
}

Usabilla.setFormDidClose(() => {
  isFormOpen = false 
})

// The following code goes in a component that renders a feedback button
useFocusEffect(
  React.useCallback(() => {
    const onBackPress = () => {
      Usabilla.onBackPressed();
      // Stop propagation of event when form is open, we don't want to also trigger a back on the router
      return isFormOpen;
    };

    BackHandler.addEventListener('hardwareBackPress', onBackPress);

    return () =>
      BackHandler.removeEventListener('hardwareBackPress', onBackPress);
  }, [])
);
```

This isn't ideal for a few reasons but mainly because we need to wrap Usabilla functionality which could lead to not keeping `isFormOpen` in sync.

It would be great if the SDK would allow hooking into events of form open/close, ideally I'd like to write something like this:

```js
const [isFormOpen, setIsFormOpen] = useState(false)

useEffect(() => {
  const onFormStateChange = state => setIsFormOpen(state.isOpen)

  Usabilla.addEventListener('formStateChange', onFormStateChange)

  return () => Usabilla.removeEventListener('formStateChange', onFormStateChange)
}, [])

useFocusEffect(
  React.useCallback(() => {
    const onBackPress = () => {
      Usabilla.onBackPressed();
      // Stop propagation of event when form is open, we don't want to also trigger a back on the router
      return isFormOpen;
    };

    BackHandler.addEventListener('hardwareBackPress', onBackPress);

    return () =>
      BackHandler.removeEventListener('hardwareBackPress', onBackPress);
  }, [isFormOpen])
);
```

I would much prefer a pub/sub approach here for the form state over a `getFormState()` imperative method as the event listener can be made reactive and is immune to async/concurrent bugs.

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
