### ISSUE TITLE
Usabilla Campaign appears randomly

### ISSUE THREAD

**Issue by sherif-cyber** [usabilla/usabilla-u4a-react-native#182]
- Creating New Campaign with **Custom Events**

will lead to display this campaign randomly in app even (event fired or not)

so in some cases campaign is fired in old versions of app which doesn't contain new event.

**Comment by stodorovicc** [comment]
Hi @sherif-cyber , thanks for reaching out.

Could you please update to the latest version of our iOS SDK using Pods? We fixed that issue in our v6.12.2 release.

You can update using "cd ios && pod update Usabilla && cd .."

Let us know if that worked for you.

Thanks,
Slobodan

**Comment by SherifMega** [comment]
Thank you @stodorovicc for Quick Reply

is there any workaround available to avoid that happening in old releases

campaign config or something like that 🤔 

i mean when publishing new version and enable campaign (old release issue still happens - new releases fixed)

**Comment by stodorovicc** [comment]
Hi @sherif-cyber , unfortunately there is nothing that can be done in campaign config, unless you update to the latest version of our SDK. Another thing to note is that this issue started from v6.12.0 when we introduced Standard events, if you're using version older than that, there should be no issues with campaign displaying randomly.

Thanks,
Slobodan

**Comment by SherifMega** [comment]
Thanks 🙏  i will validate that at newer SDK version
