### ISSUE TITLE
DialogFragment overlap by status bar on Android

### ISSUE THREAD

**Issue by pickle636** [usabilla/usabilla-u4a-react-native#196]
I have a issue with overlapping when displaying a form. Form layout is located under the status bar as you can see on the screenshot:
![Screenshot_1685110428](https://github.com/usabilla/usabilla-u4a-react-native/assets/50166722/650320d4-dcbf-464c-9dbd-12dcff0d93ba)
This only happens on devices without display cutout. Here's what it looks like with display cutout:

![Screenshot_1685113211](https://github.com/usabilla/usabilla-u4a-react-native/assets/50166722/19137edb-44ef-440c-858c-758410865368)
As you can see the status bar changes color.

My **style.xml**:
```
<style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
    <item name="android:windowTranslucentStatus">true</item>
    <item name="colorPrimary">@color/colorPrimary</item>
    ...
  </style>
```
Tested on Android 13.
Is there a way to prevent this?

**Comment by Alex-us** [comment]
Have the same issue on Android 13 (Pixel 4 API 33)

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
