### ISSUE TITLE
Post install script: unable to build with yarn

### ISSUE THREAD

**Issue by serrg** [usabilla/usabilla-u4a-react-native#197]
Hi all, I have ran into issue with building the `1.0.1` package with yarn:

```
➤ YN0007: │ usabilla-react-native@npm:1.0.1 must be built because it never has been before or the last one failed
➤ YN0009: │ usabilla-react-native@npm:1.0.1 couldn't be built successfully (exit code 127, logs can be found here: /private/var/folders/fb/4gtkj1z11014lzs9fmy27wqh0000gn/T/xfs-2f9d6201/build.log)
```

where `/private/var/folders/fb/4gtkj1z11014lzs9fmy27wqh0000gn/T/xfs-2f9d6201/build.log` is:
```
# This file contains the result of Yarn building a package (usabilla-react-native@npm:1.0.1)
# Script name: postinstall

command not found: if
command not found: then
command not found: fi
```

I have found that is is caused by posinstall scripts:
```
  "scripts": {
    "postinstall": "if [ -d \".git/hooks/\" ]; then cp .script/commit_check.sh .git/hooks/commit-msg; fi",
```

What is the reason to modify git hooks with post install script in this case? In my opinion it should not affect the project workspace and post install script should be removed.

**Comment by henrique-c-ladeira-dti** [comment]
I am also running into this issue on windows. On mac (and probably linux) it works fine.
It seems that this post-script is written in bash.

I also think it should be removed completely or maybe add a devDependency like https://www.npmjs.com/package/run-script-os so that it doesn't run into trouble when executing on windows.

**Comment by maxivanovwildix** [comment]
Same issue on mac

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
