### ISSUE TITLE
Campaign is not working

### ISSUE THREAD

**Issue by jsmr04** [usabilla/usabilla-u4a-react-native#202]
Hello!

I'm trying to implement Usabilla on my React Native app. I've created a feedback form and a campaign. The form works fine, but the campaign is not showing up on my app.

I followed the documentation, the SDK is initialized by passing the App Id and then the event is called. I created a custom event called 'login' and tried the standard event 'LAUNCH' also.

I thought I had something wrong with my code, so I cloned the sample app that is attached to this repo, but the campaign is not showing up on the sample app either.

This is my campaign

<img width="1522" alt="Screenshot 2023-07-25 at 7 43 22 PM" src="https://github.com/usabilla/usabilla-u4a-react-native/assets/3135326/6691a7fc-0085-4ecc-8e3f-531b53bc9b8c">

**Comment by stodorovicc** [comment]
Hi @jsmr04 , would you be able to share some more information on below?

Platform:  Android/iOS 
SDK version:
Device & Device OS version:
Steps to reproduce the issue:

Bridge & Bridge version:
FormId / AppId / CampaignId:
Stack trace / logs:

Thanks in advance,
Slobodan

**Comment by jsmr04** [comment]
@stodorovicc yeah, sure

Platform: Android/iOS
SDK version:
**Android**
`        buildToolsVersion = "33.0.0"
        minSdkVersion = 23
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "23.1.7779620"`

**iOS**
Xcode: 14.2

Device & Device OS version: iPhone 13 (simulator), Pixel 2 (emulator), and Huawei Mate Lite 20 (real device)
Steps to reproduce the issue:

1- Create a new app campaign on Usabilla with the custom event 'login' (please look at the image attached in my first comment)
2- Initialize SDK: 
`usabilla.initialize('60bb380f-7fd8-4d99-8a7b-85bf28f834f4')`
3-Send event:
`usabilla.sendEvent('login')`

As far as I understand, the campaign should appear after sending the event to Usabilla, but the campaign doesn't show up

Bridge & Bridge version:  1.0.1 and 1.0.2
FormId / AppId / CampaignId:

AppId: 60bb380f-7fd8-4d99-8a7b-85bf28f834f4
CampaignId: 7af11a31-940e-41fd-9eee-de5300b7ac3f - unlike the feedback form id, I can't see the campaign id on the Overview page. I got this id from the Usabilla preview app. I hope it works.

Stack trace / logs: no logs

**Comment by jsmr04** [comment]
There was a problem with the campaign setup, the "start" page was missing and this caused the campaign to not appear in the app.
