### ISSUE TITLE
Cannot add the same observer with different lifecycles

### ISSUE THREAD

**Issue by dturneyWR** [usabilla/usabilla-u4a-react-native#210]
Seeing the following issue in production:

```
Caused by java.lang.IllegalArgumentException: Cannot add the same observer with different lifecycles
       at androidx.lifecycle.LiveData.observe(LiveData.java:199)
       at com.usabilla.reactnative.ubform.UsabillaBridge.onHostResume(UsabillaBridge.java:288)
       at com.facebook.react.bridge.ReactContext.onHostResume(ReactContext.java:308)
```

Configuration:
```
"react-native": "0.72.5"
"usabilla-react-native": "1.0.2"
```

**Comment by dturneyWR** [comment]
Hi @emulroy9,

I'm not sure, i've been trying to repro the issue locally, but currently struggling to activate our Usabilla feedback form to be able to test. Will provide more information once i'm able to reproduce this myself. But it was only since we upgraded React Native to this version we are encountering this issue

My assumption is that Usabilla is loading the feedback form, and the app is then crashing `onResume` but unsure why, as we only have a single activity in our app

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
