### ISSUE TITLE
Get Feedback form on Android does not send screenshot to feedback website

### ISSUE THREAD

**Issue by VladPopax-Wirtek** [usabilla/usabilla-u4a-react-native#211]
Hello,

On Android/MIUI devices after you upload a photo with camera or from gallery or even the screenshot taken with `loadFeedbackFormWithCurrentViewScreenshot` and Submit the form, the sent photo won't appear on the get feedback website for the respective feedback data, while the other stuff (text, rating, etc.) will appear.

This issue is happening only on Android/MIUI phones, while on iOS is working as expected.

Versions used:
 "react": "18.2.0",
 "react-native": "0.71.3",
 "usabilla-react-native": "^1.0.4"

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
