### ISSUE TITLE
Cannot build with XCode 10

### ISSUE THREAD

**Issue by mattSydney** [usabilla/usabilla-u4a-react-native#37]
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler:

**Comment by Rifinio** [comment]
@mattSydney Thank you for bring this issue up! we are working on it and we'll let you know once it is released.

**Comment by tzengerink** [comment]
@mattSydney We've released [v0.6.0](https://github.com/usabilla/usabilla-u4a-react-native/releases/tag/v0.6.0) which should solve your issue.
