### ISSUE TITLE
'Usabilla.framework` not available from `ReactNativeUsabilla/Frameworks

### ISSUE THREAD

**Issue by kbanashek** [usabilla/usabilla-u4a-react-native#43]
I'm able to compile my iOS project with usabilla implemented, however I cannot complete the step around: 
'Drag and drop the `Usabilla.framework` from `ReactNativeUsabilla/Frameworks` and check the `code sign on copy`

as the framework is not available in my list:
![image](https://user-images.githubusercontent.com/2280402/51002055-164f7480-1500-11e9-9258-b114be5fa917.png)

**Comment by MikaelAmborn** [comment]
I'm having the same problem. How did you solve it @kbanashek?
