### ISSUE TITLE
UsabillaSampleApp Form is not rendering on iOS with valid formId

### ISSUE THREAD

**Issue by kbanashek** [usabilla/usabilla-u4a-react-native#44]
The UsabillaSampleApp will not render on iOS emulators with a valid formId.
No exceptions are being thrown, app crashes

**Comment by dan11218** [comment]
Hi @kbanashek, thanks for getting in touch!

From your email earlier I understand you are able to render this in Android, but not in iOS, correct?  May you please provide the name of the account so we may take a closer look? Can you confirm if 'UsabillaSampleApp' is a Form or Campaign? I look forward to your response!

**Comment by kbanashek** [comment]
It appears that on iOS, the appID is required at least with our application. Something to note moving forward perhaps in the documentation.
