### ISSUE TITLE
Upgrade to iOS sdk 6.1.0

### ISSUE THREAD

**Issue by MikaelAmborn** [usabilla/usabilla-u4a-react-native#52]
Please upgrade the usabilla iOS skd to v6.1.0 to support Xcode 10.2

**Comment by torkvell** [comment]
Hi @MikaelAmborn ,

Thanks for reaching out on this. We're already aware of this and are working on a release for the React Native bridge. If time is of the essence for you on this, then you could get the latest version from our [iOS SDK](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk) and replace it with the current framework.

I hope this clarifies and helps you out. Please let me know if there is anything else I can help out with.

**Comment by duytrann** [comment]
Hi @torkvell,

Any updates on this?

**Comment by torkvell** [comment]
Hi @duytrann ,

This fix is part of our current sprint and will be included in our next release. I will update this ticket once the upgrade is done. In the meantime I would like to thank you all for your patience on this and please let me know if there is anything else I can assist you with.

**Comment by mattSydney** [comment]
how long is your sprint!? 😂

**Comment by torkvell** [comment]
Hi @MikaelAmborn,

Pardon for the delay on this. Due to other prioritizations, this hasn't been picked up yet. Our team is currently fully focused on implementing our new Xamarin bridge. I will update this ticket once it's done. 

Thank you for your patience on this.

**Comment by torkvell** [comment]
Hi all,

While you guys are waiting for the release I would like to provide you with some steps on how you can work around this for now:

1. Get the latest Usabilla.framework from [GitHub Usabilla iOS Repository](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk)

2. Replace the current framework in your apps nod-modules / usabilla-react-native with the downloaded one from the iOS repo:
![unnamed](https://user-images.githubusercontent.com/40064170/57086477-790e8b00-6cfe-11e9-8137-7a8d93664f6a.png)

3. Lastly, you must also change the settings of UsabillaReactNative in the included libraries to swift 4:
![2](https://user-images.githubusercontent.com/40064170/57086745-fc2fe100-6cfe-11e9-8a8f-ce1c9b75f1b5.png)

I hope this helps for now. I will keep you updated once we have the new release fixed.

**Comment by klaevv** [comment]
Hi @torkvell, can you estimate when the update to support Xcode 10.2 will be out?

**Comment by torkvell** [comment]
Hi @klaevv ,

I do not want to come with any time estimates on this yet. Our team is still fully focused on finishing up the last tasks in relation to the Xamarin bridge we just released. When those tasks are done we will move on with updating the React Native bridge.

I hope this clarifies. Let me know if you need anything else.

**Comment by duytrann** [comment]
Hi @torkvell,

I don't feel very comfortable modifying my node modules on a production build. Especially with a high profile app like that of Ajax.
I would have liked to have seen this done at the time of the Xcode 10.2 release, but as we've missed that window already I would (and probably many others) like this to be fixed in a proper release asap.

**Comment by mattSydney** [comment]
Hi , We pay a lot money for your library. When are you going to fix it please? This is not the first time this has happened with new xcode releases

**Comment by torkvell** [comment]
Hi @mattSydney ,

Our developers are currently working on the update, please give it some time. 

Let me know if you need anything else.

**Comment by klaevv** [comment]
Hi @torkvell, 

Are you now able to estimate when the update for Xcode 10.2 is finished?

**Comment by torkvell** [comment]
Hi @klaevv ,

You can find the latest release with our SDK version 6.2.0 here: https://github.com/usabilla/usabilla-u4a-react-native/releases
