### ISSUE TITLE
Module compile issue on XCode Version 11.0 beta 2 (11M337n)

### ISSUE THREAD

**Issue by philbenoit-ibsa** [usabilla/usabilla-u4a-react-native#60]
After upgrading to 0.8.0.

During build time I receive an error message.

> Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

I see you have supplied an update for the swift package, will we get an update for the RN package soon as well?

**Comment by torkvell** [comment]
Hi @philbenoit-ibsa ,

We won't provide an update to this yet as our SDK team is currently focused on implementing new features. You will still be able to fetch the latest Usabilla.framework from GitHub Usabilla iOS repository: [https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/releases)

I hope this helps for now. I will keep you updated once we have published a new release.

**Comment by torkvell** [comment]
New release ready: https://github.com/usabilla/usabilla-u4a-react-native/releases
