### ISSUE TITLE
Passive feedback form crashing on iOS & not closing properly on Android

### ISSUE THREAD

**Issue by klaevv** [usabilla/usabilla-u4a-react-native#61]
# Opening the passive feedback form on iOS

A crash occurs if the back button is pressed. Also selecting the stars option and feeding in the gender info crashes our app. The error in both cases is `*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <UIViewController: 0x7fef40622520>.'`.

I tested this with the latest release v0.8.0. 😎 

# Closing the passive feedback form on Android

On a positive note, the form doesn't crash on Android. However, since there's no method to close the form with, navigating back with the hardware button closes our app.

# Screenshots

Here's the feedback form. Other than opening, it really doesn't work on our app's iOS version. 🔥 🚒 

![Screenshot_1563347282](https://user-images.githubusercontent.com/5346910/61354415-ccfb2b80-a87a-11e9-90a7-3321d5db2888.png)

**Comment by klaevv** [comment]
We have this problem in our production build on iOS. The form crashes frequently.

How quickly can you guys get this crashing phenomenon resolved?

**Comment by torkvell** [comment]
Hi @klaevv ,

I just did a test with our test app that we have provided in this repository: [https://github.com/usabilla/usabilla-u4a-react-native/tree/master/UsabillaSampleApp](https://github.com/usabilla/usabilla-u4a-react-native/tree/master/UsabillaSampleApp)

I have no problem providing feedback through star ratings or with closing the form. Also tested with the latest release v0.8.0. I would advise you to check the [app.js](https://github.com/usabilla/usabilla-u4a-react-native/blob/master/UsabillaSampleApp/App.js) script in the example app to see how you can implement Usabilla successfully. 

I hope this helps. Please let me know if you have any further questions.

**Comment by klaevv** [comment]
I double checked and the implementation is in accordance with your example app. It does work on Android, so the implementation is probably ok. 

I also debugged the callbacks and noticed that `setFormDidLoadSuccessfully` calls its function reference twice, which could be why the crahs occurs. Other than that, I don't see anything unusual with the app regarding the feedback form. 

Do you think the double callback is the issue?

**Comment by torkvell** [comment]
Hi @klaevv ,

If you've followed the same implementation as outlined in the example app then there might be an issue with that specific `formID` for iOS specifically. 

What I can do is to test with your `formID` on iOS, just to be sure there are no account-specific issues you're running into. Also, is there a specific device you're testing with or does the crash occur on all iOS devices? Feel free to send your `Usabilla account name` and `formID` to support@usabilla.com.

Looking forward to your reply.

**Comment by klaevv** [comment]
The crash has occurred on multiple iOS devices. I'll send the details via mail. Thanks.

**Comment by torkvell** [comment]
Hi @klaevv,

I just had a test with your formID and I'm able to leave feedback and closing the form without any issues. Here is the feedback item. 
![2019-07-22 at 16 54](https://user-images.githubusercontent.com/40064170/61642739-c79a4880-aca1-11e9-8385-3ec47e2230d4.png)
![2019-07-22 at 16 59](https://user-images.githubusercontent.com/40064170/61642888-147e1f00-aca2-11e9-8f33-99eb846ab642.png)


If you have any other steps to reproduce this, then please let me know.

**Comment by klaevv** [comment]
I was able to get the form working with your demo project. However it remains a mystery why the crash occurs on iOS with our app.

While our app is more complex than the provided example, the passive feedback form is implemented exactly as the documentation says. I had to disable it on our iOS version for now 🌚

**Comment by torkvell** [comment]
Hi @klaevv ,

Great to hear you made it work with the example project. Then you at least have something to cross-reference with. If the implementation is done in the same way then maybe it's time to look at the differentiators between the working example and yours. There might be some other underlying things interfering with the Usabilla form. Following the stack trace should at least give you the source of the initiator of the crash.

**Comment by torkvell** [comment]
Support delivered through email, closing thread
