### ISSUE TITLE
Add support for React Native 0.60 autolinking

### ISSUE THREAD

**Issue by ksulliva** [usabilla/usabilla-u4a-react-native#65]
It would be nice for this library to support the new [autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) feature of RN 0.60. I understand that some additional setup would likely still be required, but it would be especially helpful on iOS.

Just to give one example of the possible benefits, the current linking process does not work on iOS if you are using custom schemes and build configurations. So if you have more than just Debug and Release (e.g. Staging, QA, etc.) configurations, building the project will fail. This is fixed for libraries that use autolinking, as Cocoapods will handle additional configurations correctly.

**Comment by torkvell** [comment]
Hi @ksulliva ,

Thanks for reaching out to support on this. I'm happy to clarify.

Our SDK team will have a look into this so we eventually can include it in one of our next releases. 

I would like to thank you for your feedback and please let us know if there is anything else we can assist you with.

**Comment by quyentran-agilityio** [comment]
+1

**Comment by mink-ang** [comment]
+1

**Comment by keshcreations** [comment]
Hi @ksulliva,

Thank you for taking the time to consider how we could improve our product.

Our team released a new version of our React Native SDK with auto-linking. I would like to invite you to have a look at it and try it out. Installing this version of the SDK is different from the previous versions hence why we updated our documentation as well.

Feel free to share any feedback you might have with us.
