### ISSUE TITLE
Feedback screen cut off at top

### ISSUE THREAD

**Issue by ryandt** [usabilla/usabilla-u4a-react-native#74]
Our Usabilla feedback form on Android is getting cut off at the top of the screen. The amount of "cut off" appears equal to the height of the status bar, so my assumption is that the screen is drawing underneath the status bar.

It's worth noting that our `MainActivity` and `Application` classes do not contain any custom theming or styling and we are not subclassing `ReactFragmentActivity` due to the fact that we are currently subclassing `com.reactnativenavigation.NavigationActivity` for native app navigation support and Java doesn't support multiple inheritance.

React Native version: 0.60.5
Usabilla version: 0.8.1

![feedback-screen](https://user-images.githubusercontent.com/4073952/64880059-f0451b80-d61c-11e9-8b8b-0414976d877d.png)

**Comment by torkvell** [comment]
Hi @ryandt,

Thanks for reaching out on this. I'm happy to assist with this. Do you have a link to a production app where this is replicated? It looks like you have no header in your app, thus resulting in the cut-off.

Looking forward to your reply.

**Comment by ryandt** [comment]
Hey @torkvell. I'm a little hesitant to share out a project with our app ID. Is there another way to debug this? Something worth noting: we noticed this after updating to RN 0.60.5. We weren't seeing this issue before.

>It looks like you have no header in your app, thus resulting in the cut-off.

By header, do you mean the app bar? If so, it looks like the app bar is being rendered at the bottom of the screen on Android (see screenshot above).

**Comment by torkvell** [comment]
Hi @ryandt ,

Pardon for the late reply on this. I just did a test with the latest release v 0.8.2 and there is no cut-off in the header there:
![2019-10-25 at 16 21](https://user-images.githubusercontent.com/40064170/67578857-9ec39c80-f743-11e9-91f9-656b05c6d5bc.png)

This was tested using our sample app: https://github.com/usabilla/usabilla-u4a-react-native/tree/master/UsabillaSampleApp

I hope this helps. If there is anything else please let me know.

**Comment by ryandt** [comment]
@torkvell I'm still seeing the cut-off issue on my end using 0.8.2. I even tried copying the AppTheme in the sample app and using a 7.0 device to reduce the differences between our tests but to no avail. I will try to find some time next week or the week after to break out the code I'm using into a demo app that can be shared.

**Comment by torkvell** [comment]
Hi @ryandt,

Please let us know if this is still an issue and if you've been able to replicate it in a test app.
