### ISSUE TITLE
Sample app not working

### ISSUE THREAD

**Issue by mink-ang** [usabilla/usabilla-u4a-react-native#81]
RN version: 0.60.5
Xcode version: 11.1
NPM version: 6.13.0

Steps to reproduce:
1. Clone the repo
2. npm install in ./usabilla-u4a-react-native
3. npm install in ./usabilla-u4a-react-native/UsabillaSampleApp
4. npm start
5. Run react-native run-ios

Error 1: 
![Screen Shot 2019-11-14 at 1 41 45 pm](https://user-images.githubusercontent.com/41883348/68823678-975f3580-06e8-11ea-9085-fc28f62d89d6.png)

Error 2:

Users/xxxx/Documents/git/usabilla-u4a-react-native/ios/ReactNativeUsabilla/UsabillaInterface.swift:10:8: error: module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Users/****/Documents/git/usabilla-u4a-react-native/ios/Usabilla.framework/Modules/Usabilla.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
import Usabilla
       ^
** BUILD FAILED **
The following commands produced analyzer issues:
	Analyze /Users/xxxx/Documents/git/usabilla-u4a-react-native/UsabillaSampleApp/node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp normal x86_64
	Analyze /Users/xxxx/Documents/git/usabilla-u4a-react-native/UsabillaSampleApp/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp normal x86_64
(2 commands with analyzer issues)
The following build commands failed:
	CompileSwift normal x86_64 /Users/xxxx/Documents/git/usabilla-u4a-react-native/ios/ReactNativeUsabilla/UsabillaInterface.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by torkvell** [comment]
https://github.com/usabilla/usabilla-u4a-react-native/issues/82
